# Generated by Django 4.1.7 on 2023-09-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stuname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stuid',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='kumarsateesh838@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='message',
            field=models.CharField(default='message', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(default='+91XXXXXXXXXX', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='subject', max_length=50),
        ),
    ]
