# Generated by Django 4.1.7 on 2023-09-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_stuname_student_name_remove_student_stuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
